# SETUP
baseurl = ""
publishdir = "public"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy","taxonomyTerm","sitemap"]

[params]
    author = "ttntm"
    DateForm = "02.01.2006"
    showReadTime = 1
    title = "Twin.Lab Atlas"
    description = "Ein Atlas aktueller Twin-Pojekt."